eureka:
  client:
    serviceUrl:
      defaultZone: http://book_eureka:8761/eureka/
server:
  port: 5962
spring:
  application:
    name: Book_Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authormanagement
          uri: http://author_management:5960
          predicates:
            - Path=/authors/**
          filters:
            - AuthenticationFilter
        - id: bookmanagement
          uri: http://bookmanagement:5959
          predicates:
            - Path=/bookapi/**
          filters:
            - AuthenticationFilter
        - id: Book_Authentication
          uri: http://book_authentication:5961
          predicates:
            - Path=/auth/**